#!/usr/bin/env bash
# FLAI v9.0 — Скрипт развёртывания на одном сервере

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# ── Цвета ──
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()  { echo -e "${GREEN}[INFO]${NC} $1"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

# ── Проверка зависимостей ──
check_prereqs() {
    info "Проверка зависимостей..."
    command -v docker &>/dev/null     || error "Docker не установлен. Установите Docker."
    command -v docker compose &>/dev/null || error "Плагин Docker Compose не установлен."
    command -v git &>/dev/null        || error "Git не установлен."
    if ! command -v nvidia-smi &>/dev/null; then
        warn "Видеокарта NVIDIA не обнаружена — ускорение на GPU будет недоступно."
    fi
    if docker info 2>/dev/null | grep -q "Runtimes.*nvidia"; then
        info "NVIDIA Docker runtime обнаружен."
    elif command -v nvidia-smi &>/dev/null; then
        warn "nvidia-smi найден, но nvidia-container-runtime не обнаружен в Docker."
    fi
    info "Зависимости проверены."
}

# ── Настройка окружения ──
setup_env() {
    if [[ -f .env ]]; then
        warn ".env уже существует — пропускаем настройку."
        return
    fi
    info "Создаю .env из .env.example..."
    cp .env.example .env
    SECRET=$(python3 -c "import secrets; print(secrets.token_hex(32))" 2>/dev/null || openssl rand -hex 32)
    sed -i "s/SECRET_KEY=.*/SECRET_KEY=$SECRET/" .env
    info ".env создан. Отредактируйте его для настройки моделей, URL и параметров."
}

# ── Директории данных ──
setup_dirs() {
    info "Создаю директории данных..."
    mkdir -p data/uploads data/documents data/db_backups data/slm
    chown -R 1000:1000 data 2>/dev/null || warn "Не удалось изменить владельца data/ — выполните с sudo."
}

# ── Проверка .env ──
validate_env() {
    if [[ ! -f .env ]]; then
        warn ".env не найден — сначала запустите deploy.sh."
        return
    fi
    local errors=0
    grep -qP '^SECRET_KEY=\S+' .env 2>/dev/null || { warn "SECRET_KEY не задан в .env"; errors=1; }
    grep -qP '^DATABASE_URL=\S+' .env 2>/dev/null || { warn "DATABASE_URL не задан в .env"; errors=1; }
    [[ "$errors" -eq 1 ]] && warn "Отредактируйте .env перед продолжением."
}

# ── Генерация минимального конфига llama-swap ──
generate_llama_swap_config() {
    local CONFIG_DIR="llama-swap-config"
    mkdir -p "$CONFIG_DIR"

    if [[ -f "$CONFIG_DIR/llama-swap.yaml" ]]; then
        return
    fi

    info "Генерирую минимальный конфиг llama-swap..."

    local CHAT_MODEL="Qwen3-4B-Instruct-2507-Q4_0"
    if command -v nvidia-smi &>/dev/null; then
        local GPU_NAME
        GPU_NAME=$(nvidia-smi --query-gpu=name --format=csv,noheader,nounits 2>/dev/null | head -1 | tr -d ' ')
        if [[ "${GPU_NAME,,}" =~ (rtx 5060|rtx 5070|rtx 5080|rtx 5090|blackwell|b100|b200|gb200|gb10) ]]; then
            CHAT_MODEL="Qwen3-4B-Instruct-2507-MXFP4_MOE"
        fi
    fi

    cat > "$CONFIG_DIR/llama-swap.yaml" << YAML
# Auto-generated by deploy.sh — replaced by web app on startup
default_model: chat
models:
  - model: /models/${CHAT_MODEL}.gguf
    name: chat
    ctx_size: 16384
YAML
}

# ── Вспомогательная функция скачивания моделей ──
HF_DOWNLOAD() {
    local repo="$1" file="$2" dest="$3"
    local url="https://huggingface.co/$repo/resolve/main/$file"
    info "Скачиваю $file из HuggingFace..."
    local dir="$(dirname "$dest")"
    mkdir -p "$dir"
    
    # Retry download up to 3 times
    for attempt in 1 2 3; do
        curl -L --progress-bar -o "$dest" "$url"
        
        # Check if file is valid (more than 1KB)
        local size=$(stat -c%s "$dest" 2>/dev/null || echo "0")
        if [[ "$size" -gt 1024 ]]; then
            info "Успешно скачано: $file ($size bytes)"
            return 0
        else
            warn "Попытка $attempt не удалась, повторяю..."
            rm -f "$dest"
            sleep 2
        fi
    done
    error "Не удалось скачать $file после 3 попыток"
}

# ── Модели llama.cpp ──
download_llamacpp_models() {
    info "Скачиваю модели llama.cpp..."
    local MODEL_DIR="services/llamacpp/models"
    local VRAM_MB=0
    local IS_BLACKWELL=false
    local CHAT_MODEL=""
    local REASONING_MODEL=""

    if command -v nvidia-smi &>/dev/null; then
        VRAM_MB=$(nvidia-smi --query-gpu=memory.total --format=csv,noheader,nounits 2>/dev/null | head -1 | tr -d ' ')
    fi

    # Определяем архитектуру GPU — MXFP4 только на Blackwell (аппаратные FP4 тензорные ядра)
    if command -v nvidia-smi &>/dev/null; then
        local GPU_NAME
        GPU_NAME=$(nvidia-smi --query-gpu=name --format=csv,noheader,nounits 2>/dev/null | head -1 | tr -d ' ')
        if [[ "${GPU_NAME,,}" =~ (rtx 5060|rtx 5070|rtx 5080|rtx 5090|blackwell|b100|b200|gb200|gb10) ]]; then
            IS_BLACKWELL=true
        fi
    fi

    if [[ "$IS_BLACKWELL" == true ]]; then
        CHAT_MODEL="Qwen3-4B-Instruct-2507-MXFP4_MOE"
        REASONING_MODEL="gpt-oss-20b-mxfp4"
    else
        CHAT_MODEL="Qwen3-4B-Instruct-2507-Q4_0"
        REASONING_MODEL="gpt-oss-20b-Q4_K_M"
    fi

    # Чат-модель (роутер) — квантизация зависит от архитектуры GPU
    if [[ ! -f "$MODEL_DIR/${CHAT_MODEL}.gguf" ]]; then
        info "Скачиваю ${CHAT_MODEL}.gguf (чат/роутер)..."
        HF_DOWNLOAD "unsloth/Qwen3-4B-Instruct-2507-GGUF" \
            "${CHAT_MODEL}.gguf" \
            "$MODEL_DIR/${CHAT_MODEL}.gguf"
    else
        warn "${CHAT_MODEL}.gguf уже есть — пропускаю."
    fi

    # Модель рассуждений — выбор по VRAM и архитектуре
    if [[ "$VRAM_MB" -ge 16000 ]]; then
        # 16GB+ — полная модель (квантизация зависит от архитектуры)
        if [[ ! -f "$MODEL_DIR/${REASONING_MODEL}.gguf" ]]; then
            info "Скачиваю ${REASONING_MODEL}.gguf (рассуждения, уровень 16GB+)..."
            HF_DOWNLOAD "unsloth/gpt-oss-20b-GGUF" \
                "${REASONING_MODEL}.gguf" \
                "$MODEL_DIR/${REASONING_MODEL}.gguf"
        else
            warn "${REASONING_MODEL}.gguf уже есть — пропускаю."
        fi
    else
        # 12GB и 8GB — Gemma 4 E4B Q4_0 (~4,8 ГБ)
        if [[ ! -f "$MODEL_DIR/gemma-4-E4B-it-Q4_0.gguf" ]]; then
            info "Скачиваю gemma-4-E4B-it-Q4_0.gguf (рассуждения)..."
            HF_DOWNLOAD "unsloth/gemma-4-E4B-it-GGUF" \
                "gemma-4-E4B-it-Q4_0.gguf" \
                "$MODEL_DIR/gemma-4-E4B-it-Q4_0.gguf"
        else
            warn "gemma-4-E4B-it-Q4_0.gguf уже есть — пропускаю."
        fi
    fi

    # Мультимодальная модель — выбор по VRAM
    if [[ "$VRAM_MB" -ge 12000 ]]; then
        if [[ ! -d "$MODEL_DIR/Qwen3VL-8B-Instruct-Q4_K_M" ]]; then
            info "Скачиваю Qwen3VL-8B-Instruct-Q4_K_M (мультимодальная, уровень 12GB+)..."
            mkdir -p "$MODEL_DIR/Qwen3VL-8B-Instruct-Q4_K_M"
            HF_DOWNLOAD "Qwen/Qwen3-VL-8B-Instruct-GGUF" \
                "Qwen3VL-8B-Instruct-Q4_K_M.gguf" \
                "$MODEL_DIR/Qwen3VL-8B-Instruct-Q4_K_M/Qwen3VL-8B-Instruct-Q4_K_M.gguf"
            HF_DOWNLOAD "Qwen/Qwen3-VL-8B-Instruct-GGUF" \
                "mmproj-Qwen3VL-8B-Instruct-F16.gguf" \
                "$MODEL_DIR/Qwen3VL-8B-Instruct-Q4_K_M/mmproj-F16.gguf"
        else
            warn "Qwen3VL-8B-Instruct-Q4_K_M уже есть — пропускаю."
        fi
    elif [[ "$VRAM_MB" -ge 8000 ]]; then
        info "VRAM ${VRAM_MB}MB: скачиваю лёгкую мультимодальную (Qwen3VL-4B)..."
        if [[ ! -d "$MODEL_DIR/Qwen3VL-4B-Instruct-Q4_K_M" ]]; then
            mkdir -p "$MODEL_DIR/Qwen3VL-4B-Instruct-Q4_K_M"
            HF_DOWNLOAD "Qwen/Qwen3-VL-4B-Instruct-GGUF" \
                "Qwen3VL-4B-Instruct-Q4_K_M.gguf" \
                "$MODEL_DIR/Qwen3VL-4B-Instruct-Q4_K_M/Qwen3VL-4B-Instruct-Q4_K_M.gguf" || \
            warn "Не удалось скачать лёгкую мультимодальную. Запасной вариант: 8B."
            HF_DOWNLOAD "Qwen/Qwen3-VL-4B-Instruct-GGUF" \
                "mmproj-Qwen3VL-4B-Instruct-F16.gguf" \
                "$MODEL_DIR/Qwen3VL-4B-Instruct-Q4_K_M/mmproj-F16.gguf" || true
            if [[ ! -f "$MODEL_DIR/Qwen3VL-4B-Instruct-Q4_K_M/Qwen3VL-4B-Instruct-Q4_K_M.gguf" ]]; then
                warn "Qwen3VL-4B недоступна на HuggingFace, скачиваю 8B вместо..."
                rm -rf "$MODEL_DIR/Qwen3VL-4B-Instruct-Q4_K_M"
                mkdir -p "$MODEL_DIR/Qwen3VL-8B-Instruct-Q4_K_M"
                HF_DOWNLOAD "Qwen/Qwen3-VL-8B-Instruct-GGUF" \
                    "Qwen3VL-8B-Instruct-Q4_K_M.gguf" \
                    "$MODEL_DIR/Qwen3VL-8B-Instruct-Q4_K_M/Qwen3VL-8B-Instruct-Q4_K_M.gguf"
                HF_DOWNLOAD "Qwen/Qwen3-VL-8B-Instruct-GGUF" \
                    "mmproj-Qwen3VL-8B-Instruct-F16.gguf" \
                    "$MODEL_DIR/Qwen3VL-8B-Instruct-Q4_K_M/mmproj-F16.gguf"
            fi
        fi
    else
        if [[ ! -d "$MODEL_DIR/Qwen3VL-8B-Instruct-Q4_K_M" ]]; then
            info "VRAM неизвестна: скачиваю Qwen3VL-8B-Instruct-Q4_K_M..."
            mkdir -p "$MODEL_DIR/Qwen3VL-8B-Instruct-Q4_K_M"
            HF_DOWNLOAD "Qwen/Qwen3-VL-8B-Instruct-GGUF" \
                "Qwen3VL-8B-Instruct-Q4_K_M.gguf" \
                "$MODEL_DIR/Qwen3VL-8B-Instruct-Q4_K_M/Qwen3VL-8B-Instruct-Q4_K_M.gguf"
            HF_DOWNLOAD "Qwen/Qwen3-VL-8B-Instruct-GGUF" \
                "mmproj-Qwen3VL-8B-Instruct-F16.gguf" \
                "$MODEL_DIR/Qwen3VL-8B-Instruct-Q4_K_M/mmproj-F16.gguf"
        fi
    fi

    # Модель эмбеддингов — подходит для всех уровней
    if [[ ! -f "$MODEL_DIR/bge-m3-Q8_0.gguf" ]]; then
        info "Скачиваю bge-m3-Q8_0.gguf (эмбеддинги)..."
        HF_DOWNLOAD "gpustack/bge-m3-GGUF" \
            "bge-m3-Q8_0.gguf" \
            "$MODEL_DIR/bge-m3-Q8_0.gguf"
    else
        warn "bge-m3-Q8_0.gguf уже есть — пропускаю."
    fi
}

# ── Модели Stable Diffusion ──
download_sd_cpp_models() {
    info "Скачиваю модели stable-diffusion.cpp..."
    local DIFF_DIR="services/sd_cpp/models/diffusion_models"
    local VAE_DIR="services/sd_cpp/models/vae"
    local TXT_DIR="services/sd_cpp/models/text_encoders"

    # Z-Image Turbo (генерация изображений)
    if [[ ! -f "$DIFF_DIR/z_image_turbo-Q8_0.gguf" ]]; then
        info "Скачиваю z_image_turbo-Q8_0.gguf..."
        HF_DOWNLOAD "leejet/Z-Image-Turbo-GGUF" \
            "z_image_turbo-Q8_0.gguf" "${DIFF_DIR}/z_image_turbo-Q8_0.gguf"
    else
        warn "z_image_turbo-Q8_0.gguf уже есть — пропускаю."
    fi

    # Flux.2 Klein 4B (редактирование изображений)
    if [[ ! -f "$DIFF_DIR/flux-2-klein-4b-Q8_0.gguf" ]]; then
        info "Скачиваю flux-2-klein-4b-Q8_0.gguf (редактирование)..."
        HF_DOWNLOAD "leejet/FLUX.2-klein-4B-GGUF" \
            "flux-2-klein-4b-Q8_0.gguf" "${DIFF_DIR}/flux-2-klein-4b-Q8_0.gguf"
    else
        warn "flux-2-klein-4b-Q8_0.gguf уже есть — пропускаю."
    fi

    # VAE (для генерации)
    if [[ ! -f "$VAE_DIR/ae.safetensors" ]]; then
        info "Скачиваю ae.safetensors (VAE для генерации)..."
        HF_DOWNLOAD "Comfy-Org/z_image_turbo" \
            "split_files/vae/ae.safetensors" "${VAE_DIR}/ae.safetensors"
    else
        warn "ae.safetensors уже есть — пропускаю."
    fi

    # VAE (для редактирования)
    if [[ ! -f "$VAE_DIR/flux2_ae.safetensors" ]]; then
        info "Скачиваю flux2_ae.safetensors (VAE для редактирования)..."
        HF_DOWNLOAD "Comfy-Org/flux2-dev" \
            "split_files/vae/flux2-vae.safetensors" \
            "${VAE_DIR}/flux2_ae.safetensors"
    else
        warn "flux2_ae.safetensors уже есть — пропускаю."
    fi

    # Кодировщик текста (общий с чат-моделью)
    if [[ ! -f "$TXT_DIR/Qwen3-4B-Instruct-2507-Q4_K_M.gguf" ]]; then
        info "Скачиваю Qwen3-4B-Instruct-2507-Q4_K_M.gguf (кодировщик текста)..."
        # Симлинк из чат-модели, если уже скачана
        if [[ -f "services/llamacpp/models/Qwen3-4B-Instruct-2507-Q4_K_M.gguf" ]]; then
            info "Чат-модель уже скачана — создаю симлинк..."
            ln -sf "../../llamacpp/models/Qwen3-4B-Instruct-2507-Q4_K_M.gguf" \
                "$TXT_DIR/Qwen3-4B-Instruct-2507-Q4_K_M.gguf"
        else
            HF_DOWNLOAD "unsloth/Qwen3-4B-Instruct-2507-GGUF" \
                "Qwen3-4B-Instruct-2507-Q4_K_M.gguf" \
                "${TXT_DIR}/Qwen3-4B-Instruct-2507-Q4_K_M.gguf"
        fi
    else
        warn "Qwen3-4B-Instruct-2507-Q4_K_M.gguf уже есть — пропускаю."
    fi
}

# ── Модели LTX-Video ──
download_ltx_video_models() {
    info "Скачиваю модели LTX-Video..."
    local VIDEO_DIR="services/ltx_video/models"

    if [[ ! -f "$VIDEO_DIR/ltxv-2b-0.9.8-distilled.safetensors" ]]; then
        info "Скачиваю ltxv-2b-0.9.8-distilled.safetensors..."
        HF_DOWNLOAD "Lightricks/LTX-Video" \
            "ltxv-2b-0.9.8-distilled.safetensors" \
            "$VIDEO_DIR/ltxv-2b-0.9.8-distilled.safetensors"
    else
        warn "ltxv-2b-0.9.8-distilled.safetensors уже есть — пропускаю."
    fi

    if [[ ! -d "$VIDEO_DIR/t5_encoder/text_encoder" ]]; then
        info "Скачиваю T5 text encoder (PixArt T5-XXL, ~18 ГБ на диске)…"
        bash "$SCRIPT_DIR/services/ltx_video/download-t5-encoder.sh"
    else
        warn "T5 text encoder уже есть — пропускаю."
    fi
}

# ── Модели TTS (синтез речи) ──
download_tts_models() {
    info "Скачиваю модели TTS (Piper)..."
    local TTS_DIR="services/piper/piper_models"
    mkdir -p "$TTS_DIR"
    # Английский (мужской)
    if [[ ! -f "$TTS_DIR/en_US-ryan-medium.onnx" ]]; then
        info "Скачиваю en_US-ryan-medium.onnx..."
        HF_DOWNLOAD "rhasspy/piper-voices" \
            "en/en_US/ryan/medium/en_US-ryan-medium.onnx" \
            "$TTS_DIR/en_US-ryan-medium.onnx"
        HF_DOWNLOAD "rhasspy/piper-voices" \
            "en/en_US/ryan/medium/en_US-ryan-medium.onnx.json" \
            "$TTS_DIR/en_US-ryan-medium.onnx.json"
    fi
    # Английский (женский)
    if [[ ! -f "$TTS_DIR/en_US-ljspeech-medium.onnx" ]]; then
        info "Скачиваю en_US-ljspeech-medium.onnx..."
        HF_DOWNLOAD "rhasspy/piper-voices" \
            "en/en_US/ljspeech/medium/en_US-ljspeech-medium.onnx" \
            "$TTS_DIR/en_US-ljspeech-medium.onnx"
        HF_DOWNLOAD "rhasspy/piper-voices" \
            "en/en_US/ljspeech/medium/en_US-ljspeech-medium.onnx.json" \
            "$TTS_DIR/en_US-ljspeech-medium.onnx.json"
    fi
    # Русский (мужской)
    if [[ ! -f "$TTS_DIR/ru_RU-dmitri-medium.onnx" ]]; then
        info "Скачиваю ru_RU-dmitri-medium.onnx..."
        HF_DOWNLOAD "rhasspy/piper-voices" \
            "ru/ru_RU/dmitri/medium/ru_RU-dmitri-medium.onnx" \
            "$TTS_DIR/ru_RU-dmitri-medium.onnx"
        HF_DOWNLOAD "rhasspy/piper-voices" \
            "ru/ru_RU/dmitri/medium/ru_RU-dmitri-medium.onnx.json" \
            "$TTS_DIR/ru_RU-dmitri-medium.onnx.json"
    fi
    # Русский (женский)
    if [[ ! -f "$TTS_DIR/ru_RU-irina-medium.onnx" ]]; then
        info "Скачиваю ru_RU-irina-medium.onnx..."
        HF_DOWNLOAD "rhasspy/piper-voices" \
            "ru/ru_RU/irina/medium/ru_RU-irina-medium.onnx" \
            "$TTS_DIR/ru_RU-irina-medium.onnx"
        HF_DOWNLOAD "rhasspy/piper-voices" \
            "ru/ru_RU/irina/medium/ru_RU-irina-medium.onnx.json" \
            "$TTS_DIR/ru_RU-irina-medium.onnx.json"
    fi
}

# ── Модели Whisper ASR ──
download_whisper_models() {
    info "Скачиваю модель Whisper ASR (Systran/faster-whisper-medium)..."
    local CACHE_DIR="data/hf-cache"
    mkdir -p "$CACHE_DIR/hub"

    # Проверка: если модель уже скачана — пропускаем
    local MODEL_DIR="$CACHE_DIR/hub/models--Systran--faster-whisper-medium"
    if [[ -d "$MODEL_DIR" && -f "$MODEL_DIR/snapshots/"*"/model.bin" ]]; then
        info "Модель Whisper уже скачана."
        return 0
    fi

    # Скачивание через huggingface_hub (Python)
    info "Скачиваю ~1.5 ГБ — это может занять несколько минут..."
    python3 -c "
from huggingface_hub import snapshot_download
import os, sys

os.environ['HF_HUB_DOWNLOAD_TIMEOUT'] = '600'
try:
    path = snapshot_download(
        'Systran/faster-whisper-medium',
        cache_dir='$CACHE_DIR',
        ignore_patterns=['*.h5', '*.ot', '*.msgpack']
    )
    print(f'OK: модель скачана в {path}')
except Exception as e:
    print(f'ERROR: {e}')
    sys.exit(1)
" && info "Модель Whisper успешно скачана." || warn "Не удалось скачать модель Whisper. ASR будет недоступен."
}

# ── Сборка и запуск ──
build_and_launch() {
    local PROFILE=""
    [[ "$WITH_IMAGE_GEN" == "true" ]] && PROFILE="$PROFILE --profile with-image-gen"
    [[ "$WITH_VOICE" == "true" ]] && PROFILE="$PROFILE --profile with-voice"
    [[ "$WITH_RAG" == "true" ]]    && PROFILE="$PROFILE --profile with-rag"
    [[ "$WITH_VIDEO" == "true" ]]  && PROFILE="$PROFILE --profile with-video"
    [[ "$WITH_SLM" == "true" ]]    && PROFILE="$PROFILE --profile with-slm"
    [[ "$WITH_SEARCH" == "true" ]] && PROFILE="$PROFILE --profile with-search"

    COMPOSE_FILE="docker-compose.gpu.yml"
    info "Режим GPU — используется GPU compose файл."

    # Определяем уровень VRAM
    local VRAM_MB=0
    if command -v nvidia-smi &>/dev/null; then
        VRAM_MB=$(nvidia-smi --query-gpu=memory.total --format=csv,noheader,nounits 2>/dev/null | head -1 | tr -d ' ')
    fi
    if [[ "$VRAM_MB" -ge 16000 ]]; then
        info "VRAM: ${VRAM_MB}MB (уровень: 16GB+) — полная производительность (gpt-oss-20b рассуждения)"
    elif [[ "$VRAM_MB" -ge 12000 ]]; then
        info "VRAM: ${VRAM_MB}MB (уровень: 12GB) — хорошая посадка (Gemma 4 E4B рассуждения)"
    elif [[ "$VRAM_MB" -ge 8000 ]]; then
        info "VRAM: ${VRAM_MB}MB (уровень: 8GB) — тесно (Gemma 4 E4B рассуждения)"
    else
        warn "VRAM: ${VRAM_MB}MB — менее 8GB минимума. Производительность будет сильно ограничена."
    fi

    # Удаляем старые контейнеры во избежание конфликтов
    info "Останавливаю старые контейнеры (если есть)..."
    docker compose -f "$COMPOSE_FILE" down --remove-orphans 2>/dev/null || true

    info "Собираю Docker-образы..."
    docker compose -f "$COMPOSE_FILE" $PROFILE build

    info "Запускаю сервисы..."
    docker compose -f "$COMPOSE_FILE" $PROFILE up -d

    info "Ожидаю запуск сервисов..."
    sleep 10

    local STATUS
    STATUS=$(curl -s http://localhost:5000/health 2>/dev/null | python3 -c "import sys,json; print(json.load(sys.stdin).get('status','unknown'))" 2>/dev/null || echo "недоступен")
    if [[ "$STATUS" == "ok" ]]; then
        info "FLAI v9.0 запущен! Откройте http://localhost:5000 в браузере."
    else
        warn "Проверка здоровья: $STATUS — проверьте 'docker compose logs' для деталей."
    fi
}

# ── Тесты ──
run_tests() {
    info "Запускаю тесты..."
    pip install -e ".[test]" -q 2>/dev/null || pip install -r requirements.txt -q 2>/dev/null
    pytest --tb=short -q 2>&1 || warn "Некоторые тесты не прошли — проверьте вывод выше."
}

# ── Справка ──
usage() {
    cat <<'USAGE'
FLAI v9.0 — Скрипт развёртывания

Использование: ./deploy-ru.sh [ОПЦИИ]

Опции:
  --with-voice        Развернуть Whisper ASR + Piper TTS
  --with-rag          Развернуть Qdrant для RAG (поиск по документам)
  --with-image-gen    Развернуть stable-diffusion.cpp для генерации/редактирования
                      (по умолчанию: отключено, используйте этот флаг для включения)
  --with-video        Развернуть LTX-Video для генерации видео
  --with-slm          Развернуть SuperLocalMemory для долговременной памяти
                      (по умолчанию: отключено, используйте этот флаг для включения)
  --download-models   Скачать GGUF/safetensors модели из HuggingFace
  --run-tests         Запустить тесты после развёртывания
  --help, -h          Показать эту справку

Размеры скачиваемых моделей (примерно):
  llama.cpp:
    Qwen3-4B-Instruct-2507 MXFP4 (чат, Blackwell)   ~2,0 ГБ
    Qwen3-4B-Instruct-2507 Q4_0 (чат, другие GPU)   ~2,4 ГБ
    Gemma 4 E4B Q4_0 (рассуждения, 8/12ГБ)          ~4,8 ГБ
    gpt-oss-20b MXFP4 (рассуждения, 16ГБ+, Blackwell) ~12 ГБ
    gpt-oss-20b Q4_K_M (рассуждения, 16ГБ+, другие)  ~12 ГБ
    Qwen3VL-8B (мультимодальная, 12GB+)           ~5,5 ГБ
    Qwen3VL-4B (мультимодальная, 8GB)             ~2,5 ГБ
    bge-m3 (эмбеддинги)                            ~1,5 ГБ
  Генерация изображений (Z-Image Turbo) ~6,5 ГБ
  Редактирование (Flux.2 Klein 4B)    ~5 ГБ
  Видео (LTX-Video 2B)                ~5,9 ГБ
  T5 text encoder (PixArt T5-XXL)     ~18 ГБ (на диске, float32)
  TTS (Piper)                         ~0,2 ГБ
  SLM embedding model                ~0,5 ГБ (предзагружается при сборке Docker-образа)
USAGE
}

# ── Разбор аргументов ──
WITH_VOICE=false
WITH_RAG=false
WITH_IMAGE_GEN=false
WITH_VIDEO=false
WITH_SLM=false
WITH_SEARCH=false
DOWNLOAD_MODELS=false
RUN_TESTS=false

for arg in "$@"; do
    case "$arg" in
        --with-voice)     WITH_VOICE=true ;;
        --with-rag)       WITH_RAG=true ;;
        --with-image-gen) WITH_IMAGE_GEN=true ;;
        --with-video)     WITH_VIDEO=true ;;
        --with-slm)       WITH_SLM=true ;;
        --with-search)    WITH_SEARCH=true ;;
        --download-models) DOWNLOAD_MODELS=true ;;
        --run-tests)      RUN_TESTS=true ;;
        --help|-h)        usage; exit 0 ;;
    esac
done

# ── Основной запуск ──
main() {
    echo "============================================"
    echo "  FLAI v9.0 — Скрипт развёртывания"
    echo "============================================"
    echo ""

    check_prereqs
    setup_dirs
    setup_env
    validate_env
    generate_llama_swap_config

    if [[ "$DOWNLOAD_MODELS" == "true" ]]; then
        download_llamacpp_models
        download_sd_cpp_models
        download_tts_models
        [[ "$WITH_VIDEO" == "true" ]] && download_ltx_video_models
        [[ "$WITH_VOICE" == "true" ]] && download_whisper_models
    fi

    build_and_launch

    if [[ "$RUN_TESTS" == "true" ]]; then
        run_tests
    fi

    echo ""
    echo "============================================"
    info "Развёртывание завершено!"
    echo "============================================"
    echo "  Веб-интерфейс: http://localhost:5000"
    echo "  Здоровье:      http://localhost:5000/health"
    echo "  Логи:          docker compose -f $COMPOSE_FILE logs -f"
    echo "  Остановка:     docker compose -f $COMPOSE_FILE down --remove-orphans"
    echo "============================================"
}

main "$@"