# melotts
services:
  melotts:
    build:
      context: .
      dockerfile: Dockerfile.melotts
    container_name: melotts
    restart: unless-stopped
    ports:
      - "8888:8888" # Forwarding the API and WebUI access port
    networks:
      - flai_network
    # Uncomment for GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

networks:
  flai_network:
    external: true