use_default_settings: true

search:
  formats:
    - html
    - json

server:
  secret_key: "flai-searxng-change-me-in-production"
  bind_address: "0.0.0.0"
  limiter: false

ui:
  static_use_hash: true

engines:
  - name: google news
  - name: bing news
  - name: yahoo news
  - name: yahoo
    disabled: false
  - name: bing
    disabled: false
  - name: mojeek
    disabled: false
  - name: marginalia
    disabled: false
  - name: presearch
    disabled: false
  - name: qwant
    disabled: false
  - name: yandex
    disabled: false
  - name: swisscows news
    disabled: false
